const chatLog=document.querySelector('#chatLog'),chatForm=document.querySelector('#chatForm'),chatInput=document.querySelector('#chatInput'),urgentDialog=document.querySelector('#urgentDialog'),installDialog=document.querySelector('#installDialog'),installButton=document.querySelector('#installButton'),connectionStatus=document.querySelector('#connectionStatus');let deferredInstallPrompt=null;
const normalize=text=>text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const answers=[
{terms:['no puedo hablar','labios azules','confusion','somnolencia','me ahogo mucho','rescate no funciona','no puedo respirar'],type:'danger',html:'<strong>Puede tratarse de una crisis grave.</strong><p>Sigue tu plan de crisis y llama al <strong>112 ahora</strong>. Siéntate erguido, no te tumbes y no conduzcas tú mismo.</p>'},
{terms:['crisis','ataque de asma','empeoro rapido','muchos pitos'],type:'warning',html:'<strong>Actúa según tu plan escrito.</strong><p>Utiliza el inhalador de rescate que tengas pautado y valora la respuesta. Si te cuesta hablar, estás exhausto o confuso, notas labios azulados o no mejoras suficientemente, llama al <strong>112</strong>.</p>'},
{terms:['mas mi inhalador de rescate','mucho rescate','salbutamol','ventolin','terbutalina'],type:'warning',html:'<strong>Necesitar más rescate suele indicar pérdida de control.</strong><p>No aumentes indefinidamente las dosis por tu cuenta. Sigue tu plan escrito y solicita revisión si lo necesitas repetidamente, te despiertas por la noche o limita tu actividad. El tratamiento del asma debe incluir medicación antiinflamatoria con corticoide inhalado.</p>'},
{terms:['inhalador de mantenimiento','controlador','corticoide inhalado','mantenimiento'],html:'<strong>El tratamiento de mantenimiento reduce la inflamación y previene crisis.</strong><p>Úsalo con la frecuencia indicada aunque te encuentres bien. No lo suspendas por tu cuenta. Si contiene corticoide, enjuágate la boca tras la dosis cuando corresponda.</p>'},
{terms:['como uso mi inhalador','tecnica inhalatoria','camara espaciadora','inhalador'],html:'<strong>La técnica cambia según el dispositivo.</strong><ol><li>Vacía los pulmones antes de inhalar, sin soplar dentro del aparato.</li><li>Sella bien los labios.</li><li>Cartucho presurizado: inspira lenta y profundamente al pulsar. Polvo seco: inspira rápida y profundamente.</li><li>Mantén el aire 5–10 segundos si puedes.</li></ol><p>Con cartucho presurizado, una cámara espaciadora facilita la coordinación. Revisa la técnica con tu dispositivo real.</p>'},
{terms:['formoterol','mart','air','ics-formoterol'],html:'<strong>Algunas pautas utilizan corticoide-formoterol como mantenimiento y también como rescate.</strong><p>Otras emplean un inhalador de rescate diferente. No intercambies estrategias: sigue exactamente el plan correspondiente a tus inhaladores y conoce el máximo diario indicado.</p>'},
{terms:['ejercicio','deporte','correr'],html:'<strong>Con buen control, el asma no debería impedirte hacer ejercicio.</strong><p>Calienta progresivamente, lleva el rescate indicado y sigue la prevención prescrita. Si aparecen síntomas frecuentes con el esfuerzo, conviene revisar control, técnica y tratamiento, no abandonar automáticamente la actividad.</p>'},
{terms:['desencadenante','alergia','polen','acaro','humo','frio'],html:'<strong>Los desencadenantes varían entre personas.</strong><p>Evita humo y vapeo. Reduce la exposición a alérgenos solo cuando exista relación demostrada. Infecciones, contaminación, aire frío, ejercicio y algunos fármacos también pueden influir. Un tratamiento correcto reduce la sensibilidad a muchos desencadenantes.</p>'},
{terms:['flujo maximo','peak flow','peak-flow','pem'],html:'<strong>El flujo máximo se interpreta respecto a tu mejor valor personal.</strong><p>Mídelo siempre de forma comparable y registra el mejor de tres intentos. Las zonas habituales son orientativas; tu plan puede establecer límites distintos.</p>'},
{terms:['prednisona','corticoide oral','deflazacort'],html:'<strong>Los corticoides orales se reservan para situaciones concretas.</strong><p>Inicia el ciclo solo si figura en tu plan de acción o te lo indica un profesional. No uses restos de tratamientos anteriores ni prolongues la pauta por tu cuenta.</p>'},
{terms:['biologico','mepolizumab','benralizumab','dupilumab','omalizumab','tezepelumab'],html:'<strong>Los biológicos se utilizan en determinados fenotipos de asma grave.</strong><p>Reducen exacerbaciones y corticoides en pacientes seleccionados. Mantén el resto del tratamiento hasta que tu unidad indique cambios y registra cualquier reacción tras la administración.</p>'},
{terms:['que es asma','asma'],html:'<strong>El asma es una enfermedad inflamatoria de las vías respiratorias con síntomas variables.</strong><p>Puede causar tos, pitos, opresión y falta de aire. Un control adecuado permite normalmente una vida activa y reduce el riesgo de crisis.</p>'}
];
function addMessage(html,role='assistant',type=''){const article=document.createElement('article');article.className=`message ${role} ${type}`.trim();role==='user'?article.textContent=html:article.innerHTML=html;chatLog.appendChild(article);chatLog.scrollTop=chatLog.scrollHeight}
function respond(text){const value=normalize(text),match=answers.find(item=>item.terms.some(term=>value.includes(term)));setTimeout(()=>match?addMessage(match.html,'assistant',match.type||''):addMessage('<strong>No quiero darte una respuesta poco fiable.</strong><p>Puedo ayudarte con control del asma, crisis, mantenimiento y rescate, técnica inhalatoria, ejercicio, desencadenantes, flujo máximo y tratamientos biológicos.</p>'),260)}
function submitPrompt(text){const clean=text.trim();if(!clean)return;addMessage(clean,'user');respond(clean);chatInput.value='';chatInput.style.height=''}
chatForm.addEventListener('submit',event=>{event.preventDefault();submitPrompt(chatInput.value)});chatInput.addEventListener('input',()=>{chatInput.style.height='auto';chatInput.style.height=`${Math.min(chatInput.scrollHeight,130)}px`});chatInput.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();submitPrompt(chatInput.value)}});document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>submitPrompt(button.dataset.prompt)));
function switchView(name){document.querySelectorAll('.tab').forEach(tab=>{const active=tab.dataset.view===name;tab.classList.toggle('is-active',active);tab.setAttribute('aria-selected',String(active))});document.querySelectorAll('.view').forEach(view=>{const active=view.id===`${name}View`;view.classList.toggle('is-active',active);view.hidden=!active})}
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>switchView(tab.dataset.view)));document.querySelectorAll('[data-plan-prompt]').forEach(button=>button.addEventListener('click',()=>{switchView('chat');submitPrompt(button.dataset.planPrompt)}));document.querySelector('#urgentButton').addEventListener('click',()=>urgentDialog.showModal());document.querySelector('#planCrisis').addEventListener('click',()=>urgentDialog.showModal());
document.querySelector('#controlForm').addEventListener('submit',event=>{event.preventDefault();const count=new FormData(event.currentTarget).getAll('control').length,result=document.querySelector('#controlResult');result.className='result-card';if(count===0)result.innerHTML='<h3>Asma aparentemente bien controlada</h3><p>Continúa el tratamiento pautado. Buen control no significa que debas suspenderlo.</p>';else if(count<=2){result.classList.add('warning');result.innerHTML='<h3>Asma parcialmente controlada</h3><p>Revisa adherencia, técnica inhalatoria y desencadenantes. Si es un cambio reciente o persiste, solicita revisión de tu plan.</p>'}else{result.classList.add('danger');result.innerHTML='<h3>Asma mal controlada</h3><p>Necesitas revisar pronto el tratamiento y la técnica. Si estás empeorando ahora o el rescate no funciona suficientemente, utiliza tu plan de crisis y solicita atención urgente.</p>'}result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'})});
document.querySelector('#peakForm').addEventListener('submit',event=>{event.preventDefault();const best=Number(document.querySelector('#peakBest').value),today=Number(document.querySelector('#peakToday').value),percent=Math.round(today/best*100),result=document.querySelector('#peakResult');result.className='result-card';if(today>best*1.35){result.classList.add('warning');result.innerHTML='<h3>Revisa los datos introducidos</h3><p>El valor de hoy es mucho mayor que tu mejor valor personal. Comprueba unidades, técnica y cuál es realmente tu referencia estable.</p>'}else if(percent>=80)result.innerHTML=`<h3>Zona orientativa verde: ${percent}%</h3><p>Si también estás sin síntomas, mantén tu tratamiento habitual. Tu plan personal puede utilizar límites diferentes.</p>`;else if(percent>=50){result.classList.add('warning');result.innerHTML=`<h3>Zona orientativa amarilla: ${percent}%</h3><p>Sigue las instrucciones de empeoramiento de tu plan. Repite la medición correctamente y solicita valoración si no recuperas tu nivel habitual.</p>`}else{result.classList.add('danger');result.innerHTML=`<h3>Zona orientativa roja: ${percent}%</h3><p>Sigue inmediatamente tu plan de crisis. Si tienes dificultad importante para respirar o no mejoras con el rescate pautado, llama al <strong>112</strong>.</p>`}result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'})});
const isStandalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(isStandalone)installButton.hidden=true;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstallPrompt=event;installButton.hidden=false});installButton.addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}installDialog.showModal()});window.addEventListener('appinstalled',()=>installButton.hidden=true);function updateConnectionStatus(){connectionStatus.hidden=navigator.onLine}addEventListener('online',updateConnectionStatus);addEventListener('offline',updateConnectionStatus);updateConnectionStatus();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
function registerWebMcpTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController(),register=tool=>Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});register({name:'ask_asthma_question',title:'Preguntar sobre asma',description:'Envía una pregunta educativa al orientador visible.',inputSchema:{type:'object',properties:{question:{type:'string',minLength:1,maxLength:500}},required:['question'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!input||typeof input.question!=='string'||!input.question.trim()||input.question.length>500)throw new Error('La pregunta debe tener entre 1 y 500 caracteres.');switchView('chat');submitPrompt(input.question);return{status:'shown',question:input.question.trim()}}});register({name:'start_asthma_control_check',title:'Comprobar control del asma',description:'Abre el cuestionario visible de control de cuatro preguntas.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(){switchView('control');return{status:'opened'}}})}registerWebMcpTools();
